{
    'name': 'Advanced Construction Management',
    'version': '1.0.0',
    'category': 'Construction',
    'summary': 'Professional construction projects management system with cost control',
    'author': 'Hesham Ahmed',
    'website': 'https://github.com/HeshamAA',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'sale',
        'account',
        'hr',
        'hr_timesheet',
        'mail',
        'web',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/construction_project_views.xml',
        'views/construction_stage_views.xml',
        'views/construction_expense_views.xml',
        'views/construction_worker_views.xml',
        'views/construction_timesheet_views.xml',
        'views/construction_subcontract_views.xml',
        'views/construction_milestone_views.xml',
        'views/construction_boq_views.xml',
        'views/construction_change_order_views.xml',
        'views/construction_equipment_views.xml',
        'views/construction_risk_views.xml',
        'views/dashboard_view.xml',
        'views/kanban_custom_view.xml',
        'views/cost_matrix_view.xml',
        'views/timeline_view.xml',
        'data/demo_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'adv_construction_management/static/src/css/dashboard.css',
            'adv_construction_management/static/src/css/kanban.css',
            'adv_construction_management/static/src/css/cost_matrix.css',
            'adv_construction_management/static/src/css/timeline.css',
            'adv_construction_management/static/src/js/dashboard_controller.js',
            'adv_construction_management/static/src/js/kanban_controller.js',
            'adv_construction_management/static/src/js/cost_matrix_controller.js',
            'adv_construction_management/static/src/js/timeline_controller.js',
        ],
        'web.assets_qweb': [
            'adv_construction_management/static/src/xml/dashboard.xml',
            'adv_construction_management/static/src/xml/kanban.xml',
            'adv_construction_management/static/src/xml/cost_matrix.xml',
            'adv_construction_management/static/src/xml/timeline.xml',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
} # type: ignore
